# Generated by Django 5.0.1 on 2024-01-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsupplier',
            name='name',
            field=models.CharField(default=None, help_text='Name of the supplier', max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='name',
            field=models.CharField(default='', help_text='Name of the supplier', max_length=127),
            preserve_default=False,
        ),
    ]
