# Generated by Django 5.0.1 on 2024-01-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingapp', '0002_historicalsupplier_name_supplier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='weight',
            field=models.FloatField(default=0, help_text='Weight of the product in kg'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0, help_text='Weight of the product in kg'),
        ),
    ]
