# Generated by Django 5.0.1 on 2024-01-18 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingapp', '0004_historicalproduct_unit_product_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='unit',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Foreign key of Product unit', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pricingapp.productunit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(help_text='Foreign key of Product unit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pricingapp.productunit'),
        ),
    ]
