# Generated by Django 5.0.1 on 2024-01-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingapp', '0007_alter_historicalquote_price_breakdown_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleet',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='historicalfleet',
            name='unit',
        ),
        migrations.AlterField(
            model_name='fleet',
            name='cost',
            field=models.JSONField(default=dict, help_text='Fleet cost'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='type',
            field=models.CharField(choices=[('GROUND', 'GROUND')], default='GROUND', help_text='Fleet type', max_length=127),
        ),
        migrations.AlterField(
            model_name='historicalfleet',
            name='cost',
            field=models.JSONField(default=dict, help_text='Fleet cost'),
        ),
        migrations.AlterField(
            model_name='historicalfleet',
            name='type',
            field=models.CharField(choices=[('GROUND', 'GROUND')], default='GROUND', help_text='Fleet type', max_length=127),
        ),
    ]
