# Generated by Django 5.0.1 on 2024-01-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingapp', '0008_remove_fleet_unit_remove_historicalfleet_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='capacity',
            field=models.FloatField(help_text='Fleet max capacity'),
        ),
        migrations.AlterField(
            model_name='historicalfleet',
            name='capacity',
            field=models.FloatField(help_text='Fleet max capacity'),
        ),
    ]
