# Generated by Django 5.0.1 on 2024-01-20 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricingapp', '0009_alter_fleet_capacity_alter_historicalfleet_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='market_price',
        ),
        migrations.RemoveField(
            model_name='historicalquoteitem',
            name='shipping_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='market_price',
        ),
        migrations.RemoveField(
            model_name='quoteitem',
            name='shipping_price',
        ),
    ]
